coworking_agendamento/urls.py
# coworking_agendamento/urls.py

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from reservas import views as reservas_views  # Importe a view index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', reservas_views.index, name='index'),
    
    # Login, logout e registro de usuários
    path('login/', auth_views.LoginView.as_view(template_name='reservas/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', reservas_views.register, name='register'),
    
    # Incluindo URLs da app 'reservas'
    path('reservas/', include('reservas.urls')),
    path('lista/', include('reservas.urls')),
    path('administrar/', reservas_views.administrar_espacos, name='administrar_espacos'),

    # URLs para gerenciamento de espaços de coworking
    path('espaco/novo/', reservas_views.editar_espaco_coworking, name='criar_espaco'),
    path('espaco/<int:espaco_id>/cadastrar-recurso/', reservas_views.cadastrar_recurso_espaco, name='cadastrar_recurso'),
    path('espaco/<int:espaco_id>/editar/', reservas_views.editar_espaco_coworking, name='editar_espaco'),
    path('excluir-imagem/<int:imagem_id>/', reservas_views.excluir_imagem, name='excluir_imagem'),

    #lista, edita e exclui reservas
    path('minhas-reservas/', reservas_views.listar_reservas, name='listar_reservas'),
    path('editar-reserva/<int:reserva_id>/', reservas_views.editar_reserva, name='editar_reserva'),
    path('excluir-reserva/<int:reserva_id>/', reservas_views.excluir_reserva, name='excluir_reserva'),
    

    # Allauth (login via contas sociais)
    path('accounts/', include('allauth.urls')),  









]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservas/urls.py
# reservas/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Página inicial que lista os espaços
    path('', views.lista_espacos, name='lista_espacos'),
   
    path('espaco/<int:espaco_id>/', views.detalhe_espaco, name='detalhe_espaco'),  # Detalhe de um espaço específico
    
    
    
    # Página para gerenciar espaços
    path('gerenciar/', views.gerenciar_espacos, name='gerenciar_espacos'),
  
    path('newsletter_signup/', views.newsletter_signup, name='newsletter_signup'),
]

reservas/models.py
# reservas/models.py
from django.db import models
from django.contrib.auth.models import User


class EspacoCoworking(models.Model):
    nome = models.CharField(max_length=100)
    endereco = models.CharField(max_length=200)
    frase_destaque = models.CharField(max_length=100, blank=True, null=True)
    descricao = models.TextField(blank=True, null=True)
    capacidade = models.IntegerField()
    preco_por_hora = models.DecimalField(max_digits=10, decimal_places=2)
   #foto = models.ImageField(upload_to='fotos/', blank=True, null=True)
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)
    prioridade = models.IntegerField(default=0, blank=True, null=True)

    # DETALHES DO ESPAÇO 
    #descricao_espaco = models.TextField(blank=True, null=True)

    # DADOS DO ESPAÇO
    palavras_chave = models.TextField(blank=True, null=True, help_text='Separado por -')
    instagram = models.URLField(max_length=255, blank=True, null=True)
    facebook = models.URLField(max_length=255, blank=True, null=True)
    linkedin = models.URLField(max_length=255, blank=True, null=True)
    nome_espaco = models.CharField(max_length=255, blank=True, null=True)
    razao_social = models.CharField(max_length=255, blank=True, null=True)
    cep = models.CharField(max_length=20, blank=True, null=True)
    pais = models.CharField(max_length=100, blank=True, null=True)
    uf = models.CharField(max_length=2, blank=True, null=True)
    cidade = models.CharField(max_length=100, blank=True, null=True)
    bairro = models.CharField(max_length=100, blank=True, null=True)
    logradouro = models.CharField(max_length=255, blank=True, null=True)
    numero = models.CharField(max_length=10, blank=True, null=True)
    complemento = models.CharField(max_length=255, blank=True, null=True)
    logo = models.ImageField(upload_to='logos/', blank=True, null=True)
    foto_horizontal = models.ImageField(upload_to='fotos_espaco/', blank=True, null=True)

    # DADOS PESSOAIS
    nome_proprietario = models.CharField(max_length=255, blank=True, null=True)
    email_proprietario = models.EmailField(blank=True, null=True)
    telefone_proprietario = models.CharField(max_length=20, blank=True, null=True)
    nome_gerente = models.CharField(max_length=255, blank=True, null=True)
    email_gerente = models.EmailField(blank=True, null=True)
    telefone_gerente = models.CharField(max_length=20, blank=True, null=True)

    # DADOS BANCÁRIOS
    titular_conta = models.CharField(max_length=255, blank=True, null=True)
    banco = models.CharField(max_length=100, blank=True, null=True)
    agencia = models.CharField(max_length=20, blank=True, null=True)
    conta = models.CharField(max_length=20, blank=True, null=True)
    tipo_conta = models.CharField(max_length=50, blank=True, null=True)
    tipo_pix = models.CharField(max_length=50, blank=True, null=True)
    pix = models.CharField(max_length=100, blank=True, null=True)


    # DIFERENCIAIS OFERECIDOS
    cafe = models.BooleanField(default=False)
    cha = models.BooleanField(default=False)
    massagem = models.BooleanField(default=False)
    outros_diferenciais = models.CharField(max_length=255, blank=True, null=True)

    # SOBRE AS ÁREAS COMUNS
    wifi = models.BooleanField(default=False)
    acessibilidade = models.BooleanField(default=False)
    acesso24h = models.BooleanField(default=False)
    playground_kids = models.BooleanField(default=False)
    ar_condicionado = models.BooleanField(default=False)
    area_alimentacao = models.BooleanField(default=False)
    biblioteca = models.BooleanField(default=False)
    cabine_call = models.BooleanField(default=False)
    cozinha = models.BooleanField(default=False)
    espaco_pet = models.BooleanField(default=False)
    espaco_convivencia = models.BooleanField(default=False)
    lounge = models.BooleanField(default=False)
    galeria_arte = models.BooleanField(default=False)
    geladeira = models.BooleanField(default=False)
    gerador_eletricidade = models.BooleanField(default=False)
    jardim = models.BooleanField(default=False)
    quadro_branco = models.BooleanField(default=False)
    recepcao = models.BooleanField(default=False)
    sala_descompressao = models.BooleanField(default=False)
    sala_jogos = models.BooleanField(default=False)
    varanda = models.BooleanField(default=False)
    vestuario = models.BooleanField(default=False)
    velocidade_internet = models.CharField(max_length=50, blank=True, null=True)

    # OUTROS SERVIÇOS OFERECIDOS NO SEU ESPAÇO
    auditorio = models.BooleanField(default=False)
    cafeteria = models.BooleanField(default=False)
    coliving = models.BooleanField(default=False)
    espaco_eventos = models.BooleanField(default=False)
    estudio_gravacao = models.BooleanField(default=False)
    restaurante = models.BooleanField(default=False)

    # FOTOS
    fotos_area_comum = models.ImageField(upload_to='fotos_areas_comuns/', blank=True, null=True)
    fotos_area_compartilhada = models.ImageField(upload_to='fotos_areas_compartilhadas/', blank=True, null=True)
    fotos_salas_privativas = models.ImageField(upload_to='fotos_salas_privativas/', blank=True, null=True)
    outras_fotos = models.ImageField(upload_to='outras_fotos/', blank=True, null=True)


    # Definindo um relacionamento com o usuário como proprietário
    proprietario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = "Espaço de Coworking"
        verbose_name_plural = "Espaços de Coworking"
        ordering = ['prioridade']  # Ordena os espaços pelo nome de forma padrão


class ImagemEspacoCoworking(models.Model):
    espaco = models.ForeignKey(EspacoCoworking, related_name='imagens', on_delete=models.CASCADE)
    imagem = models.ImageField(upload_to='fotos/')

    def __str__(self):
        return f"Imagem de {self.espaco.nome}"        





class RecursosEspacoCoworking(models.Model):
    espaco_coworking = models.ForeignKey(EspacoCoworking, on_delete=models.CASCADE, related_name='recursos')
    nome_recurso = models.CharField(max_length=100)
    descricao = models.TextField()
    quantidade = models.PositiveIntegerField()
    disponivel = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.nome_recurso} - {self.espaco_coworking.nome}"
    
    class Meta:
        verbose_name = "Recurso"
        verbose_name_plural = "Recursos"
        ordering = ['nome_recurso']  # Ordena os espaços pelo nome de forma padrão










class Reserva(models.Model):
    espaco = models.ForeignKey(EspacoCoworking, on_delete=models.CASCADE)
    usuario = models.ForeignKey( User, on_delete=models.CASCADE, blank=True, null=True)
    data_reserva = models.DateField()
    recurso = models.ForeignKey(RecursosEspacoCoworking, on_delete=models.CASCADE) 
    hora_inicio = models.TimeField(blank=True, null=True)
    hora_fim = models.TimeField(blank=True, null=True)

    def __str__(self):
        return f"{self.espaco.nome} - {self.data_reserva} - {self.hora_inicio} to {self.hora_fim}"

    class Meta:
        verbose_name = "Reserva"
        verbose_name_plural = "Reservas"
        # Ordena as reservas por data e hora
        ordering = ['data_reserva', 'hora_inicio']

    def save(self, *args, **kwargs):
        # Adicionar lógica para validação de reservas aqui, se necessário
        super().save(*args, **kwargs)

reservas/forms.py
# reservas/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone
from .models import Reserva
from .models import EspacoCoworking
from .models import RecursosEspacoCoworking






# reservas/forms.py
class ReservaForm(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = ['data_reserva', 'hora_inicio', 'hora_fim']
        widgets = {
            'data_reserva': forms.DateInput(attrs={'type': 'date'}),
            'hora_inicio': forms.TimeInput(attrs={'type': 'time'}),
            'hora_fim': forms.TimeInput(attrs={'type': 'time'}),
        }

    def __init__(self, *args, **kwargs):
        self.espaco = kwargs.pop('espaco', None)
        super(ReservaForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        data_reserva = cleaned_data.get('data_reserva')
        hora_inicio = cleaned_data.get('hora_inicio')
        hora_fim = cleaned_data.get('hora_fim')


        # Verifica se a data está no passado
        if data_reserva and data_reserva < timezone.now().date():
            print('Data passada! data_reserva: ' + str(data_reserva) + ' hoje: ' + str(timezone.now().date()))
            raise ValidationError('Não é possível fazer reservas para datas passadas.')


        # Verifica se o horário de início é anterior ao horário de fim
        if hora_inicio and hora_fim and hora_inicio >= hora_fim:
            print('Hora errada! hora_inicio: ' + str(hora_inicio) + ' hora_fim: ' + str(hora_fim))
            raise ValidationError('O horário de início deve ser anterior ao horário de fim.')
       

        # Verifica conflitos de horário usando o espaço passado na view
        if data_reserva and hora_inicio and hora_fim:
            conflitos = Reserva.objects.filter(
                espaco=self.espaco,
                data_reserva=data_reserva,
                hora_inicio__lt=hora_fim,
                hora_fim__gt=hora_inicio
            )
            if conflitos.exists():
                print('Conflitou!')
                raise ValidationError('Já existe uma reserva para este horário.')

        return cleaned_data
    
 

class EspacoCoworkingForm(forms.ModelForm):
    # Campo para upload de múltiplas imagens
    imagens = forms.FileField(required=False, widget=forms.FileInput(), help_text="Selecione as imagens para upload")

    class Meta:
        model = EspacoCoworking
        fields = '__all__'
        exclude = ['proprietario']  # Não permita que o proprietário seja alterado        


class RecursosEspacoCoworkingForm(forms.ModelForm):
    class Meta:
        model = RecursosEspacoCoworking
        fields = ['nome_recurso', 'descricao', 'quantidade', 'disponivel']

reservas/templates/reservas/administrar_coworkings.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Espaços de Coworking</title>
    <!-- Inclua os estilos CSS principais -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <!-- Integração com o Crisp -->
    <script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="c47a6fe5-4949-4d1d-8805-76f8615765ce";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>

</head>

<body>

    <!-- Header -->
    <header id="header" class="header d-flex align-items-center fixed-top">
        <div class="container-fluid position-relative d-flex align-items-center justify-content-between">

            <a href="{% url 'index' %}" class="logo d-flex align-items-center me-auto me-xl-0">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <!-- <img src="assets/img/logo.png" alt=""> -->
                <h1 class="sitename">Coworking Space</h1><span>.</span>
            </a>

            <nav id="navmenu" class="navmenu">
                <ul>
                    <li><a href="{% url 'index' %}" >Início</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'lista_espacos' %}">Reservar</a></li>
                        <li><a href="{% url 'listar_reservas' %}">Minhas reservas</a></li>
                        <li><a href="{% url 'administrar_espacos' %}" class="active">Administrar coworkings</a></li>
                    {% endif %}
                    <!--<li><a href="#spaces">Espaços</a></li>
                    <li><a href="#services">Serviços</a></li>
                    <li><a href="#pricing">Preços</a></li>
                    <li><a href="#contact">Contato</a></li>-->

                </ul>
                <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
            </nav>
            <div>
                {% if user.is_authenticated %}
                    <!-- Usuário está autenticado -->
                     
                    <form method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn-getstarted">Logout</button>
                        
                    </form>
                    
                    
                    
                {% else %}    
                    <!-- Usuário não está autenticado -->
                    <a class="btn-getstarted" href="{% url 'register' %}">Login / Registre-se</a>
                {% endif %}    
                    
            </div>


        </div>
    </header>

    <!-- Main Content -->
    <main class="main mt-5">
        <section class="section">
            <div class="container" data-aos="fade-up">
                <div class="section-title">
                    <h2>Seus Espaços de Coworking</h2>
                    <a class="btn-getstarted" href="{% url 'criar_espaco' %}"><button type="button" class="btn btn-primary btn-lg shadow">Cadastrar novo espaço</button></a>
                </div>
                <div class="row gy-4">
                    {% for espaco in espacos %}
                    <div class="col-lg-4 col-md-6">
                        <div class="card h-100 shadow-sm">
                            <!-- Carrossel -->
                            <div id="carouselEspaco{{ espaco.id }}" class="carousel slide" data-bs-ride="carousel">
                                <div class="carousel-inner">
                                    {% for imagem in espaco.imagens.all %}
                                    <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                        <img src="{{ imagem.imagem.url }}" class="d-block w-100" alt="Imagem do Espaço" style="height: 200px; object-fit: cover;">
                                    </div>
                                    {% endfor %}
                                </div>
                                <!-- Controles do Carrossel -->
                                <button class="carousel-control-prev" type="button" data-bs-target="#carouselEspaco{{ espaco.id }}" data-bs-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Anterior</span>
                                </button>
                                <button class="carousel-control-next" type="button" data-bs-target="#carouselEspaco{{ espaco.id }}" data-bs-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Próximo</span>
                                </button>
                            </div>
                            
                            <!-- Dados e botões -->
                            <div class="card-body">
                                <h5 class="card-title">{{ espaco.nome }}</h5>
                                <p class="card-text">Capacidade: {{ espaco.capacidade }} pessoas</p>
                                <a href="{% url 'detalhe_espaco' espaco.id %}" class="btn btn-primary">Detalhes</a>
                                <a href="{% url 'editar_espaco' espaco.id %}" class="btn btn-primary">Editar espaço</a>
                                <a href="{% url 'cadastrar_recurso' espaco.id %}" class="btn btn-primary">Recursos</a>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <p>Não há espaços de coworking disponíveis no momento.</p>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>

    <!-- Inclua os scripts JS principais -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/aos/aos.js' %}"></script>
    <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

reservas/templates/reservas/cadastrar_recurso.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Cadastrar Recurso do Espaço Coworking</title>

    <!-- Vendor CSS Files 
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet"> 
    <link rel="stylesheet" type="text/css" href="{% static 'reservas/styles.css' %}">
    <link href="{% static 'css/styleDna.css' %}" rel="stylesheet">-->

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'reservas/styles.css' %}">

    <style>
        .nav-tabs .nav-link {
            border: none;
            background-color: transparent;
            color: #007bff;
            font-weight: bold;
            padding: 10px 20px;
            transition: background-color 0.3s ease;
            text-align: center;
        }

        .nav-tabs .nav-link:hover {
            background-color: #f1f1f1;
        }

        .nav-tabs .nav-link.active {
            border-bottom: 2px solid #007bff;
            background-color: transparent;
            color: #007bff;
        }

        .tab-content {
            padding: 20px;
            border: 1px solid #ddd;
            border-top: none;
            background-color: #fff;
        }

        /* Adiciona um padding-top para evitar que o conteúdo fique coberto pela barra de navegação */
        body {
            padding-top: 80px; /* Ajuste esse valor conforme a altura da sua barra de navegação */
        }
    </style>

    <!-- Integração com o Crisp -->
    <script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="c47a6fe5-4949-4d1d-8805-76f8615765ce";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>
</head>

<body>

    <main class="main mt-6">

        <div class="container" data-aos="fade-up">

            <!-- Header -->
            <header id="header" class="header d-flex align-items-center fixed-top">
                <div class="container-fluid position-relative d-flex align-items-center justify-content-between">

                    <a href="{% url 'index' %}" class="logo d-flex align-items-center me-auto me-xl-0">
                        <!-- Uncomment the line below if you also wish to use an image logo -->
                        <!-- <img src="assets/img/logo.png" alt=""> -->
                        <h1 class="sitename">Coworking Space</h1><span>.</span>
                    </a>

                    <nav id="navmenu" class="navmenu">
                        <ul>
                            <li><a href="{% url 'index' %}" >Início</a></li>
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'lista_espacos' %}">Reservar</a></li>
                                <li><a href="{% url 'listar_reservas' %}">Minhas reservas</a></li>
                                <li><a href="{% url 'administrar_espacos' %}" class="active">Administrar coworkings</a></li>
                            {% endif %}
                            <!--<li><a href="#spaces">Espaços</a></li>
                            <li><a href="#services">Serviços</a></li>
                            <li><a href="#pricing">Preços</a></li>
                            <li><a href="#contact">Contato</a></li>-->

                        </ul>
                        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
                    </nav>
                    <div>
                        {% if user.is_authenticated %}
                            <!-- Usuário está autenticado -->
                            
                            <form method="post" action="{% url 'logout' %}">
                                {% csrf_token %}
                                <button type="submit" class="btn-getstarted">Logout</button>
                                
                            </form>
                            
                            
                            
                        {% else %}    
                            <!-- Usuário não está autenticado -->
                            <a class="btn-getstarted" href="{% url 'register' %}">Login / Registre-se</a>
                        {% endif %}    
                            
                    </div>


                </div>
            </header>

            <div class="row justify-content-center mt-5">    
                <div class="col-lg-8">
                    <h2>Cadastrar Recurso: {{ espaco.nome }}</h2>

                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        <div class="mb-3">
                            <label for="id_nome_recurso" class="form-label">Nome do Recurso</label>
                            <input type="text" name="nome_recurso" class="form-control w-50" id="id_nome_recurso" value="{{ form.instance.nome_recurso|default:'' }}">
                        </div>

                        <div class="mb-3">
                            <label for="id_descricao" class="form-label">Descrição</label>
                            <textarea name="descricao" class="form-control w-100" id="id_descricao" style="height: 150px;">{{ form.instance.descricao|default:'' }}</textarea>
                        </div>

                        <div class="mb-3">
                            <label for="id_quantidade" class="form-label">Quantidade</label>
                            <input type="number" name="quantidade" class="form-control w-50" id="id_quantidade" value="{{ form.instance.quantidade|default:'' }}">
                        </div>

                        <div class="mb-3">
                            <label for="id_disponivel" class="form-label">Disponível</label>
                            <input type="checkbox" name="disponivel" id="id_disponivel" {% if form.instance.disponivel %}checked{% endif %}>
                        </div>

                        <button type="submit" class="btn btn-primary mt-3">Salvar</button>
                    </form>
                </div>
            </div>
        </div>

    </main>

    <!-- Vendor JS Files -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/aos/aos.js' %}"></script>
    <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>

</body>

</html>

reservas/templates/reservas/editar_reserva.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Editar Reserva</title>
    
    <!-- Bootstrap CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'reservas/styles.css' %}">

    <!-- Integração com o Crisp -->
    <script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="c47a6fe5-4949-4d1d-8805-76f8615765ce";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>
</head>

<body>
    <style>
        .custom-container {
            max-width: 85%; /* Defina a porcentagem ou um valor fixo */
        }
    </style>
    <main class="main mt-5">
        <div class="container">
            <header id="header" class="header d-flex align-items-center ">
                <div class="container-fluid position-relative d-flex align-items-center justify-content-between">
                    <a href="{% url 'index' %}" class="logo d-flex align-items-center me-auto me-xl-0">
                        <h1 class="sitename">Coworking Space</h1>
                    </a>
                </div>
            </header>

            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <h2 class="mb-4">Editar Reserva</h2>

                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.as_p }}
                        </div>
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="{% url 'listar_reservas' %}" class="btn btn-secondary">Cancelar</a>
                    </form>
                </div>
            </div>
        </div>
    </main>

    <!-- Bootstrap JS -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>